name: Update README with WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API }}
        run: |
          curl -s "https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key=${{ secrets.WAKA_API }}" > waka_stats.json
          coding_time=$(jq -r '.data.human_readable_total' waka_stats.json)
          sed -i "s/<!--waka-->/<!--waka-->Total coding time last week: ${coding_time}/" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with WakaTime stats"
          git push
